
# compiler options
CFLAGS = -std=c99 -g -Wall
LIBS = -lm

default: echo "You must specify a target, e.g. t1, t2" 

t1:
	gcc $(CFLAGS) -o $@ test.c t1.c $(LIBS)

t2:
	gcc $(CFLAGS) -o $@ test.c t2.c $(LIBS)




